[package]
name = "lazyime"
version = "0.2.0"
edition = "2024"

[dependencies.windows]
version = "0.62.2"
features = ["Win32_UI_TextServices", "Win32_System_Com", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_Ime"]

[dependencies]
